<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-ALLOTLPS" failures="1" tests="9" name="com.automation.testcase.TC_LoginTest" time="98.482" errors="0" timestamp="2023-06-08T10:13:35 ICT" skipped="0">
  <testcase classname="com.automation.testcase.TC_LoginTest" name="TC01_LoginFirstAccount" time="7.558"/>
  <system-out/>
  <testcase classname="com.automation.testcase.TC_LoginTest" name="TC01_LoginFirstAccount" time="8.723"/>
  <system-out/>
  <testcase classname="com.automation.testcase.TC_LoginTest" name="TC01_LoginFirstAccount" time="6.750"/>
  <system-out/>
  <testcase classname="com.automation.testcase.TC_LoginTest" name="TC01_LoginFirstAccount" time="7.640"/>
  <system-out/>
  <testcase classname="com.automation.testcase.TC_LoginTest" name="TC01_LoginFirstAccount" time="5.073"/>
  <system-out/>
  <testcase classname="com.automation.testcase.TC_LoginTest" name="TC01_LoginFirstAccount" time="5.594"/>
  <system-out/>
  <testcase classname="com.automation.testcase.TC_LoginTest" name="TC01_LoginFirstAccount" time="38.074">
    <failure message="The following asserts failed:
	null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.automation.testcase.TC_LoginTest.TC01_LoginFirstAccount(TC_LoginTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC01_LoginFirstAccount -->
  <system-out>
    <![CDATA[<br><a title="Screenshot" href="C:\Users\ADMIN\eclipse-workspace\ASSIGNMENT_2_SELENIUM\.\Screenshots\Can_not_find_button_logout.png"><img alt='Can_not_find_button_logout.png'src='.\Screenshots\Can_not_find_button_logout.png'height='243' width='418'</a><br>]]>
  </system-out>
  <testcase classname="com.automation.testcase.TC_LoginTest" name="TC01_LoginFirstAccount" time="10.248"/>
  <system-out/>
  <testcase classname="com.automation.testcase.TC_LoginTest" name="TC01_LoginFirstAccount" time="8.822"/>
  <system-out/>
</testsuite> <!-- com.automation.testcase.TC_LoginTest -->
